name: gitlabsync

on:
  push:
  delete:

jobs:
  sync:
    runs-on: ubuntu-latest  # Assurez-vous de spécifier l'environnement
    name: Git Repo Sync
    steps:
      - uses: actions/checkout@v3  # Mise à jour vers la version v3
        with:
          fetch-depth: 0
      - uses: wangchucheng/git-repo-sync@v0.1.0
        with:
          target-url: https://forge.apps.education.fr/nsi-rocks/fullstack
          target-username: mathieu.nicolas
          target-token: ${{ secrets.GITLAB_TOKEN }}
